/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorCliente;
import javax.swing.JOptionPane;
import modelo.Cliente;

/**
 *
 * @author Andrea
 */
public class Buscar extends javax.swing.JPanel {

    /**
     * variable de instacia para asignar el cliente
     */
    private Cliente cliente;
    
    /**
     * constructor
     */
    public Buscar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        buscarTextField = new javax.swing.JTextField();
        RBnombre = new javax.swing.JRadioButton();
        RBcodigo = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        clienteTextField = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnDepositar = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        jLabel1.setText("Buscar");

        RBnombre.setSelected(true);
        RBnombre.setText("Nombre");
        RBnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBnombreActionPerformed(evt);
            }
        });

        RBcodigo.setText("Código");
        RBcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBcodigoActionPerformed(evt);
            }
        });

        jLabel2.setText("Cliente:");

        clienteTextField.setEnabled(false);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnDepositar.setBackground(new java.awt.Color(51, 255, 51));
        btnDepositar.setText("Depositar");
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });

        btnRetirar.setBackground(new java.awt.Color(255, 255, 102));
        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RBnombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RBcodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDepositar)
                                .addGap(38, 38, 38)
                                .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(clienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar)))
                        .addGap(8, 8, 8)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBnombre)
                    .addComponent(RBcodigo)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(clienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDepositar)
                    .addComponent(btnRetirar))
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try{
            // valida el criterio de busqueda: por nombre o por código
        if(RBnombre.isSelected())
           cliente = ControladorCliente.buscar(buscarTextField.getText());
        else if(RBcodigo.isSelected())
           cliente = ControladorCliente.buscar(Integer.parseInt(buscarTextField.getText()));
        else JOptionPane.showMessageDialog(this,"Seleccione un criterio de búsqueda");
        
        clienteTextField.setText(cliente.getNombre());
   
        }catch(Exception exception){
            JOptionPane.showMessageDialog(this, "Ocurrió un Error, Verifique los campos");
            }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // crea una instancia de panel para formulario de cliente 
        // con el constructor de modo edicion con parametro.
        ClienteGUI clienteGui = new ClienteGUI(cliente);
        
        // crea una instancia de ventana inicio con el panel de cliente
        new Ventana(clienteGui);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        try{
           {
            // lanza una ventana emergente que pide el valor a depositar
            String monto = JOptionPane.showInputDialog(this, "Ingrese el depósito");
            // lanza ventana empergente con la confirmación del deposito y el nuevo saldo
            JOptionPane.showMessageDialog(this, "Depósito agregado, el nuevo saldo es: " +
                            cliente.depositar(Double.parseDouble(monto)));                            
                } 
           }  catch(Exception exception){
          // en caso de cualquier error, se atrapa cualquier excepción.
          JOptionPane.showMessageDialog(this, "Ocurrió un Error");
      }
    }//GEN-LAST:event_btnDepositarActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
     try{   
    // lanza una ventana emergente que pide el valor a depositar
          String retiro = JOptionPane.showInputDialog(this, "Ingrese la cantidad a retirar");
    // llama el metodo reitrar de la clase cliente
          Double nuevoSaldo = cliente.retirar(Double.parseDouble(retiro));
    // valida que el retiro sea exitoso
          if (nuevoSaldo != null) {
            JOptionPane.showMessageDialog(this, "Retiro realizado, el nuevo saldo es: " +
              nuevoSaldo);
            } else {
             JOptionPane.showMessageDialog(this, "No tiene Dinero sufiente");
            }                
        }catch(Exception exception){
          // atrapa cualquier excepción
          JOptionPane.showMessageDialog(this, "Ocurrió un Error");
      }
    }//GEN-LAST:event_btnRetirarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
     // lanza una ventana emergente para confirmar si de desea borrar  
       int confrimacion = JOptionPane.showConfirmDialog(this,
                            "¿Seguro que desea borrar este cliente?", "Warning", 1);
       if (confrimacion == JOptionPane.YES_OPTION) {
             ControladorCliente.eliminar(cliente);
             JOptionPane.showMessageDialog(this, "Eliminado");
           }
                        
                        

        
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * Eventos para marcar el radio button seleccionado 
     * y desmarcar el otro
     */
    private void RBcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBcodigoActionPerformed
      RBnombre.setSelected(false);
    }//GEN-LAST:event_RBcodigoActionPerformed

    private void RBnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBnombreActionPerformed
      RBcodigo.setSelected(false);
    }//GEN-LAST:event_RBnombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RBcodigo;
    private javax.swing.JRadioButton RBnombre;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JTextField buscarTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField clienteTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
